### PR TITLE
Update to discord.py 2.0 and drop text command support

### LINKED ISSUE #51: Drop text command support
After all, it is known that this bot will not be granted access to text chats.

### PR DESCRIPTION
**Pull request by galacticwarrior9**
This PR updates the bot to `discord.py` 2.0, adding support for auto-completions, ephemeral messages and select menus. It also removes text command support due to Discord making message content a [privileged intent](https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ)  (closes #51).

### CODE REVIEW

**Comment by itzmk21** [comment]
@galacticwarrior9 Is having autocomplete for Surah names (similar to how /dua does it) a good idea? Since doing `/quran surah: 24` would say `No options match your search` which might lead the user to believe surah numbers aren't possible, despite it actually still working with numbers.

**Comment by galacticwarrior9** [comment]
I think it would work if the auto-complete only begins if (1) the user has typed at least one character and (2) said character is not a number

**Comment by galacticwarrior9** [comment]
..although I think that would still give the "No options match your search" pop-up

**Comment by itzmk21** [comment]
> ..although I think that would still give the "No options match your search" pop-up

Yeah it gives it, regardless of even if you've typed a single character

**Pull request merged**
